### ISSUE TITLE
如果需要导出的excel内容的格式有两种或者多种怎么办？

### ISSUE THREAD

**Issue by ChouJoe** [pikaz-18/pikaz-excel-js#12]
比如需要导出的excek格式：
          col1      col2  col3   col4
 row1 姓名    张三  年龄    24
row2  时间    课程   地点   教室
row3  10::12  语文    教一  402
row4  11:34  数学       ...      ....
row5  ...        .....        ....        ....

**Comment by pikaz-18** [comment]
> 比如需要导出的excek格式：
> col1 col2 col3 col4
> row1 姓名 张三 年龄 24
> row2 时间 课程 地点 教室
> row3 10::12 语文 教一 402
> row4 11:34 数学 ... ....
> row5 ... ..... .... ....

格式只取决于你的数据，比如key是1,2,3,4，内容是{1：姓名，2：张三，3：年龄，4:24}，这样依次组装你的数据格式就行

**Comment by ChouJoe** [comment]
> > 比如需要导出的excek格式：
> > col1 col2 col3 col4
> > row1 姓名 张三 年龄 24
> > row2 时间 课程 地点 教室
> > row3 10::12 语文 教一 402
> > row4 11:34 数学 ... ....
> > row5 ... ..... .... ....
> 
> 格式只取决于你的数据，比如key是1,2,3,4，内容是{1：姓名，2：张三，3：年龄，4:24}，这样依次组装你的数据格式就行

是的，我后来想明白了。 现在又有个问题，就是我引用库的时候是import {ExcelExport} from 'pikaz-excel-js';， 然后我build自己的项目后发现编译后的文件增加了6M， 请问引用的时候有没有min版本？

**Comment by pikaz-18** [comment]
> > > 比如需要导出的excek格式：
> > > col1 col2 col3 col4
> > > row1 姓名 张三 年龄 24
> > > row2 时间 课程 地点 教室
> > > row3 10::12 语文 教一 402
> > > row4 11:34 数学 ... ....
> > > row5 ... ..... .... ....
> > 
> > 
> > 格式只取决于你的数据，比如key是1,2,3,4，内容是{1：姓名，2：张三，3：年龄，4:24}，这样依次组装你的数据格式就行
> 
> 是的，我后来想明白了。 现在又有个问题，就是我引用库的时候是import {ExcelExport} from 'pikaz-excel-js';， 然后我build自己的项目后发现编译后的文件增加了6M， 请问引用的时候有没有min版本？

额，包文件已经是压缩版本了，不过应该没这么大呀，整包才2m，只用一个功能的话更少，应该是你其他地方图片之类的东西占用空间了

**Comment by pikaz-18** [comment]
> > > 比如需要导出的excek格式：
> > > col1 col2 col3 col4
> > > row1 姓名 张三 年龄 24
> > > row2 时间 课程 地点 教室
> > > row3 10::12 语文 教一 402
> > > row4 11:34 数学 ... ....
> > > row5 ... ..... .... ....
> > 
> > 
> > 格式只取决于你的数据，比如key是1,2,3,4，内容是{1：姓名，2：张三，3：年龄，4:24}，这样依次组装你的数据格式就行
> 
> 是的，我后来想明白了。 现在又有个问题，就是我引用库的时候是import {ExcelExport} from 'pikaz-excel-js';， 然后我build自己的项目后发现编译后的文件增加了6M， 请问引用的时候有没有min版本？

另外还提供了cdn，想要减少打包体积可以使用cdn

**Comment by ChouJoe** [comment]
> > > > 比如需要导出的excek格式：
> > > > col1 col2 col3 col4
> > > > row1 姓名 张三 年龄 24
> > > > row2 时间 课程 地点 教室
> > > > row3 10::12 语文 教一 402
> > > > row4 11:34 数学 ... ....
> > > > row5 ... ..... .... ....
> > > 
> > > 
> > > 格式只取决于你的数据，比如key是1,2,3,4，内容是{1：姓名，2：张三，3：年龄，4:24}，这样依次组装你的数据格式就行
> > 
> > 
> > 是的，我后来想明白了。 现在又有个问题，就是我引用库的时候是import {ExcelExport} from 'pikaz-excel-js';， 然后我build自己的项目后发现编译后的文件增加了6M， 请问引用的时候有没有min版本？
> 
> 额，包文件已经是压缩版本了，不过应该没这么大呀，整包才2m，只用一个功能的话更少，应该是你其他地方图片之类的东西占用空间了

我确定是引入这个包导致的编译文件变大，因为我把相关代码注释掉，编译文件就变小了6M。
我的代码非常简单：
引入和注册组件：
![image](https://user-images.githubusercontent.com/31032742/93837837-39ad5980-fcba-11ea-87ba-239cb08a03ae.png)
html部分：
![image](https://user-images.githubusercontent.com/31032742/93837876-577abe80-fcba-11ea-8741-19c17c9c6e70.png)
请问我这样引入有问题吗？ 有没有能减少体积的引用办法？

**Comment by ChouJoe** [comment]
我看了一下编译后的文件， 主要是map文件很大
![image](https://user-images.githubusercontent.com/31032742/93839249-f4d7f180-fcbe-11ea-8bd3-7b53122190b5.png)

**Comment by pikaz-18** [comment]
> 我看了一下编译后的文件， 主要是map文件很大
> ![image](https://user-images.githubusercontent.com/31032742/93839249-f4d7f180-fcbe-11ea-8bd3-7b53122190b5.png)

这个是source map文件，是脚手架生成的，用于生产环境定位错误，如果不需要的话，可以在vue.config.js里设置productionSourceMap: false，具体api可查看vue-cli文档https://cli.vuejs.org/zh/config/#productionsourcemap
