### ISSUE TITLE
设置某一列单元格样式

### ISSUE THREAD

**Issue by Lizy-web** [pikaz-18/pikaz-excel-js#14]
如何设置列的参数，给某一列设置样式，难道要给这一列的每个单元格设置样式吗？

**Comment by pikaz-18** [comment]
> 如何设置列的参数，给某一列设置样式，难道要给这一列的每个单元格设置样式吗？

你可以拿数据列数，比如数据有5列，循环数组["A","B","C","D","E"]然后拿到相应的单元格名称A3,B3,C3,D3,E3设置样式就行了

**Comment by Lizy-web** [comment]
> > 如何设置列的参数，给一些列设置样式，难道要给这一列的每个单元格设置样式吗？
> 
> 你可以拿数据列数，而数据有5列，遍历副本[“ A”，“ B”，“ C”，“ D”，“ E”]然后拿到相应的单元格名称A3，B3，C3， D3，E3设置样式就行了，更多单元格样式同理

有没有什么简单的方法，直接设置列的样式

**Comment by pikaz-18** [comment]
> > > 如何设置列的参数，给一些列设置样式，难道要给这一列的每个单元格设置样式吗？
> > 
> > 
> > 你可以拿数据列数，而数据有5列，遍历副本[“ A”，“ B”，“ C”，“ D”，“ E”]然后拿到相应的单元格名称A3，B3，C3， D3，E3设置样式就行了，更多单元格样式同理
> 
> 有没有什么简单的方法，直接设置列的样式

额，这个需要设置多少单元格要自己去遍历找的，因为每个人需求不一样，很难在插件中做到满足所有人的需求，所以都是这样自定义的，而且只是设置列样式的话，遍历数字生成A1，A2，A3...这样也不会麻烦呀

**Comment by Lizy-web** [comment]
> > > > 如何设置列的参数，给一些列设置样式，难道要给这一列的每个单元格设置样式吗？
> > > 
> > > 
> > > 你可以拿数据列数，而数据有5列，遍历副本[“ A”，“ B”，“ C”，“ D”，“ E”]然后拿到相应的单元格名称A3，B3，C3， D3，E3设置样式就行了，更多单元格样式同理
> > 
> > 
> > 有没有什么简单的方法，直接设置列的样式
> 
> 额，这个需要设置多少单元格要自己去遍历找的，因为每个人需求不一样，很难在插件中做到满足所有人的需求，所以都是这样自定义的，而且只是设置列样式的话，遍历数字生成A1，A2，A3...这样也不会麻烦呀

好的，谢谢
