### ISSUE TITLE
如何设置整行单元格背景颜色

### ISSUE THREAD

**Issue by JustinYD** [pikaz-18/pikaz-excel-js#17]
请问我想要设置如A1 : U1这一整行的背景颜色及字体，如何设置？或者A1: U12这种

**Comment by pikaz-18** [comment]
计算一行单元格个数，比如一行数据有21个，那就遍历A到Z中第21个到U

> 请问我想要设置如A1 : U1这一整行的背景颜色及字体，如何设置？或者A1: U12这种

https://github.com/pikaz-18/pikaz-excel-js/issues/14
参考之前的issue

**Comment by JustinYD** [comment]
> 计算一行单元格个数，比如一行数据有21个，那就遍历A到Z中第21个到U
> 
> > 请问我想要设置如A1 : U1这一整行的背景颜色及字体，如何设置？或者A1: U12这种
> 
> #14
> 参考之前的issue

好的，感谢，昨天也是用了那个方法实现的，如果能改成自定义[起，始]就更方便了

**Comment by pikaz-18** [comment]
> > 计算一行单元格个数，比如一行数据有21个，那就遍历A到Z中第21个到U
> > > 请问我想要设置如A1 : U1这一整行的背景颜色及字体，如何设置？或者A1: U12这种
> > 
> > 
> > #14
> > 参考之前的issue
> 
> 好的，感谢，昨天也是用了那个方法实现的，如果能改成自定义[起，始]就更方便了

之前有想过搞，但是有人又想一行一列某个样式，然后中间或者头尾另外的样式，个性化要求太多了，干脆给个自定义方式开发者想要什么样式自己定义就行QAQ
