### ISSUE TITLE
怎么将图片导出到excel里？

### ISSUE THREAD

**Issue by xfly334** [pikaz-18/pikaz-excel-js#2]
现在显示的都是图片地址，怎么能直接显示图片

**Comment by pikaz-18** [comment]
目前没做这功能，应用场景太少了，就没去研究QWQ

**Comment by pikaz-18** [comment]
js-table2excel，这个插件封装的也挺好的，相当于将html导出为excel了，可以直接拿去用，自由度更高，但是只能导出xls格式

**Comment by pikaz-18** [comment]
> 现在显示的都是图片地址，怎么能直接显示图片

js-table2excel，这个插件封装的也挺好的，相当于将html导出为excel了，可以直接拿去用，自由度更高，但是只能导出xls格式

**Comment by 18258750091** [comment]
[
    {
        "title":"费用科目统计(按科室)",
        "tHeader":[
            "科室名称",
            "总费用"
        ],
        "table":[
            {
                "DeptName":"全科2（儿）",
                "TotalCost":33809.09
            },
            {
                "DeptName":"东吴全科",
                "TotalCost":8542.36
            },
            {
                "DeptName":"产前检查门诊",
                "TotalCost":5508.03
            },
            {
                "DeptName":"早孕产后门诊",
                "TotalCost":2221.21
            },
            {
                "DeptName":"中医专科",
                "TotalCost":58709.28
            },
            {
                "DeptName":"全科3（外）",
                "TotalCost":93162.26
            },
            {
                "DeptName":"儿童保健科",
                "TotalCost":5372.41
            },
            {
                "DeptName":"牟山湖全科",
                "TotalCost":2973.42
            },
            {
                "DeptName":"妇科专家",
                "TotalCost":4482.04
            },
            {
                "DeptName":"全科1（内）",
                "TotalCost":334884.32
            },
            {
                "DeptName":"狮山全科",
                "TotalCost":16557.87
            },
            {
                "DeptName":"胡家全科",
                "TotalCost":2235.29
            },
            {
                "DeptName":"口腔科专家",
                "TotalCost":2083.36
            },
            {
                "DeptName":"湖山全科",
                "TotalCost":8377.7
            },
            {
                "DeptName":"魏家全科",
                "TotalCost":2964.42
            },
            {
                "DeptName":"妇科普通",
                "TotalCost":1498.22
            },
            {
                "DeptName":"陈家全科",
                "TotalCost":113.93
            },
            {
                "DeptName":"口腔科",
                "TotalCost":19749.27
            },
            {
                "DeptName":"专家门诊",
                "TotalCost":12048.23
            },
            {
                "DeptName":"防保科",
                "TotalCost":69872.9
            },
            {
                "DeptName":"妇科门诊",
                "TotalCost":33377.49
            }
        ],
        "keys":[
            "DeptName",
            "TotalCost"
        ],
        "sheetName":"表1-费用科目统计(按科室)",
        "cellStyle":[
            {
                "cell":"A1",
                "font":{
                    "sz":14,
                    "color":{
                        "rgb":"ffffff"
                    },
                    "bold":true
                }
            }
        ]
    }
]
报错 
![image](https://user-images.githubusercontent.com/68170566/87273180-f80a7080-c50a-11ea-9ecb-54d278edad38.png)

**Comment by Martin1992-ss** [comment]
我的数据是通过api 获取的， table: this.tableData, 这里提示 vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'map' of undefined"

**Comment by pikaz-18** [comment]
> 我的数据是通过api 获取的， table: this.tableData, 这里提示 vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'map' of undefined"

把你的数据打印出来看一下，这个看起来是数据要求为数组但是你传入了非数组
