### ISSUE TITLE
能不能支持修改行高

### ISSUE THREAD

**Issue by caixukunLzz** [pikaz-18/pikaz-excel-js#20]
如题

**Comment by pikaz-18** [comment]
> 如题

暂时不支持，请问需要行高做什么呢

**Comment by pikaz-18** [comment]
> 如题

如果真的想设置的话，可以在表格的keys新增一个，然后在表格数据中该key属性放入多个空格，再把列宽调窄，可以变相起到调节行高的目的

**Comment by caixukunLzz** [comment]
> > 如题
> 
> 如果真的想设置的话，可以在表格的keys新增一个，然后在表格数据中该key属性放入多个空格，再把列宽调窄，可以变相起到调节行高的目的，其实就是利用大量空格给撑高行高，不过实际需求中我没见过需要调整行高的，只碰到过调整列宽，这种需求太少见了

因为客户想要直接导出后 进行打印，而且不想手动调整excel，但是文本间距不太合适 就需要调整行高了。我刚刚试了您说的那个方法 会撑起高度 但是会留下痕迹，即便设置边框颜色和文本颜色 或者是列宽都不能完美隐藏。

**Comment by caixukunLzz** [comment]
我看了一些博客 觉得应该可以调整。 关键词是这个 ['!rows']   源码中也找到了 但是没弄明白怎么设置。

**Comment by pikaz-18** [comment]
> 我看了一些博客 觉得应该可以调整。 关键词是这个 ['!rows'] 源码中也找到了 但是没弄明白怎么设置。

嗯，如果坚持想要这个功能的话，晚上我回去看一看源码看看能不能加上，晚上会给你答复的，谢谢您的反馈

**Comment by pikaz-18** [comment]
> 我看了一些博客 觉得应该可以调整。 关键词是这个 ['!rows'] 源码中也找到了 但是没弄明白怎么设置。

不好意思，看了下js-xlsx的源码，并没有行高的设置，如果想使用这个功能只能去使用xlsxjs的付费版了，免费版无法设置行高

**Comment by pikaz-18** [comment]
> 我看了一些博客 觉得应该可以调整。 关键词是这个 ['!rows'] 源码中也找到了 但是没弄明白怎么设置。

不好意思，看了下js-xlsx的源码，并没有行高的设置，sheetjs付费版应该是支持的

**Comment by caixukunLzz** [comment]
> > 我看了一些博客 觉得应该可以调整。 关键词是这个 ['!rows'] 源码中也找到了 但是没弄明白怎么设置。
> 
> 不好意思，看了下js-xlsx的源码，并没有行高的设置，sheetjs付费版应该是支持的

好吧，辛苦了。
