### ISSUE TITLE
xls 无法打开

### ISSUE THREAD

**Issue by JieYueCoding** [pikaz-18/pikaz-excel-js#25]
文件格式无效

**Comment by pikaz-18** [comment]
> 文件格式无效

确实存在问题，看来发布一年来，你是第一个使用xls格式的，QAQ，先用xlsx吧，xls问题我稍后在看看

**Comment by zhanghaifei1997** [comment]
> > 文件格式无效
> 
> 确实存在问题，看来发布一年来，你是第一个使用xls格式的，QAQ，先用xlsx吧，xls问题我稍后在看看

现在是2022年8月5号了，催更。注意：：：我都然发现不只是xls，xlsx有的时候也无法加载，只能加载第一列序号出来

**Comment by pikaz-18** [comment]
> > > 文件格式无效
> > 
> > 
> > 确实存在问题，看来发布一年来，你是第一个使用xls格式的，QAQ，先用xlsx吧，xls问题我稍后在看看
> 
> 现在是2022年8月5号了，催更。注意：：：我都然发现不只是xls，xlsx有的时候也无法加载，只能加载第一列序号出来

尴尬，这个问题忘记了，xlsx无法加载可以给我发一个问题数据吗，我的邮箱：qq2363994579@outlook.com

**Comment by zhanghaifei1997** [comment]
> > > > 文件格式无效
> 
> > > 
> 
> > > 
> 
> > > 确实存在问题，看来发布一年来，你是第一个使用xls格式的，QAQ，先用xlsx吧，xls问题我稍后在看看
> 
> > 
> 
> > 现在是2022年8月5号了，催更。注意：：：我都然发现不只是xls，xlsx有的时候也无法加载，只能加载第一列序号出来
> 
> 
> 
> 尴尬，这个问题忘记了，xlsx无法加载可以给我发一个问题数据吗，我的邮箱：qq2363994579@outlook.com



好的👌，明天到公司
