### ISSUE TITLE
有人吧你的代码复制到了github上了

### ISSUE THREAD

**Issue by cheguang** [pikaz-18/pikaz-excel-js#28]
层主你看看 有人复制了你的代码额 ,  https://github.com/zhbittango/pikaz-excel-js  .请问只支持txt和exell吗.

**Comment by pikaz-18** [comment]
> 层主你看看 有人复制了你的代码额 , https://github.com/zhbittango/pikaz-excel-js .请问只支持txt和exell吗.

这个不叫复制，这个叫fork，是正常行为QAQ，暂时只支持xlsx文件的导入和导出

**Comment by cheguang** [comment]
> > 层主你看看别人复制了你的代码额，https://github.com/zhbittango/pikaz-excel-js。请只支持txt和exell吗。
> 
> 这个不叫复制，这个叫叉，是正常行为QAQ，暂时只支持xlsx文件的导入和导出

嗯嗯 目前用起来还可以的..
