### ISSUE TITLE
合并列之后 加入换行 不生效。

### ISSUE THREAD

**Issue by caixukunLzz** [pikaz-18/pikaz-excel-js#29]
![image](https://user-images.githubusercontent.com/56342617/120778581-0ca78b00-c559-11eb-8cbd-ef6ac0a4c19a.png)

实际自动换行是设置上的 但是行高没有变化 仍然是一行的高度。是什么问题？

**Comment by pikaz-18** [comment]
> ![image](https://user-images.githubusercontent.com/56342617/120778581-0ca78b00-c559-11eb-8cbd-ef6ac0a4c19a.png)
> 
> 实际自动换行是设置上的 但是行高没有变化 仍然是一行的高度。是什么问题？

可以发一下您的样式配置代码吗

**Comment by caixukunLzz** [comment]
// 样式
![image](https://user-images.githubusercontent.com/56342617/121318537-e9f0ea00-c93d-11eb-9691-97dd5bd3409a.png)
// 合并
![image](https://user-images.githubusercontent.com/56342617/121318607-fc6b2380-c93d-11eb-95fe-b14406b94f0d.png)
// 效果
![image](https://user-images.githubusercontent.com/56342617/121318659-09881280-c93e-11eb-8256-369dbcbf4b8a.png)

**Comment by caixukunLzz** [comment]
合并居中之后 自动换行也设置了 但是实际效果和预期不一样。

**Comment by memory1668** [comment]
应该是Excel本身的特性，参考：[EXCEL合并单元格设置自动换行后为什么行高不自动调整
](https://www.wps.cn/learning/room/d/285686)

**Comment by 2936121056** [comment]
动态数据如何合并单元格

**Comment by pikaz-18** [comment]
> 动态数据如何合并单元格

单元格合并是由merges参数控制的，只需要自己计算一下动态数据需要合并的单元格是什么，再动态更改merges就可以了

**Comment by 2936121056** [comment]
谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pikaz-18/pikaz-excel-js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月13日(星期三) 上午9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pikaz-18/pikaz-excel-js] 合并列之后 加入换行 不生效。 (#29)





  
动态数据如何合并单元格
  
单元格合并是由merges参数控制的，只需要自己计算一下动态数据需要合并的单元格是什么，再动态更改merges就可以了
