### ISSUE TITLE
导出时指定单元格格式无效

### ISSUE THREAD

**Issue by czy1026** [pikaz-18/pikaz-excel-js#35]
导出时看到格式有s
![image](https://user-images.githubusercontent.com/48408999/126088712-a2bc46f9-d70b-4d5e-82d0-134c7bed5e45.png)
但是导出后单元格并无格式
![image](https://user-images.githubusercontent.com/48408999/126088785-efb9f039-6f71-4476-8aee-e6bfe0869ffe.png)
这样会导致输入日期如：2021-07-19会被xlsx自动转换格式变成2021/07/19，这种情况如何解决呢

**Comment by pikaz-18** [comment]
> 导出时看到格式有s
> ![image](https://user-images.githubusercontent.com/48408999/126088712-a2bc46f9-d70b-4d5e-82d0-134c7bed5e45.png)
> 但是导出后单元格并无格式
> ![image](https://user-images.githubusercontent.com/48408999/126088785-efb9f039-6f71-4476-8aee-e6bfe0869ffe.png)
> 这样会导致输入日期如：2021-07-19会被xlsx自动转换格式变成2021/07/19，这种情况如何解决呢

我测试不会出现这种情况呀，我在demo表格数据中写入2021-07-19，实际显示没有问题，估计是excel不同版本的默认行为，这个暂时没有比较好的解决办法
![image](https://user-images.githubusercontent.com/44502383/126093560-b2da1f78-2861-4cbf-8a28-3c648f67f0c8.png)

**Comment by czy1026** [comment]
![image](https://user-images.githubusercontent.com/48408999/126117240-4d2a71c4-e421-41ed-8ebe-8292cd050ecf.png)
是的可能是这个问题，在js-xlsx文档中看到了这样一句话，感谢大佬
