### ISSUE TITLE
设置样式的时候cell只能设置一个单元格吗

### ISSUE THREAD

**Issue by 2360025303** [pikaz-18/pikaz-excel-js#37]
我如果设置好几个单元格一样的样式
`[
						{
							cell: 'A1',
							font: {
								sz: 14,
								color: { rgb: "ffffff" },
								bold: true,
								},
								fill: {
									fgColor: { rgb: "cccccc" },
								}
						},
						{
							cell: 'C1',
							font: {
								sz: 14,
								color: { rgb: "ffffff" },
								bold: true,
								},
								fill: {
									fgColor: { rgb: "cccccc" },
								}
						},
					]`

**Comment by pikaz-18** [comment]
> 我如果设置好几个单元格一样的样式
> `[ { cell: 'A1', font: { sz: 14, color: { rgb: "ffffff" }, bold: true, }, fill: { fgColor: { rgb: "cccccc" }, } }, { cell: 'C1', font: { sz: 14, color: { rgb: "ffffff" }, bold: true, }, fill: { fgColor: { rgb: "cccccc" }, } }, ]`

遍历你要设置样式的单元格数组，比如【‘A1’,'C1'】，返回对应的单元格样式生成新的样式数组即可

**Comment by 2360025303** [comment]
> 

谢谢大佬,你写的这个真的很方便

**Comment by pikaz-18** [comment]
> > 
> 
> 谢谢大佬,你写的这个真的很方便

感谢使用
