### ISSUE TITLE
缺少jquery

### ISSUE THREAD

**Issue by xiaoawen** [pikaz-18/pikaz-excel-js#39]
./node_modules/pikaz-excel-js/lib/PikazJsExcel.umd.min.js
Module not found: Error: Can't resolve 'jquery' in 'E:\work\smart_city2\node_modules\pikaz-excel-js\lib'

**Comment by pikaz-18** [comment]
> ./node_modules/pikaz-excel-js/lib/PikazJsExcel.umd.min.js
> Module not found: Error: Can't resolve 'jquery' in 'E:\work\smart_city2\node_modules\pikaz-excel-js\lib'

这个应该是你项目的引入jq报错，这整个库没有依赖jquery

**Comment by xiaoawen** [comment]
不会吧，我没使用这个库之前没有问题，引入之后就报了这个错误

**Comment by xiaoawen** [comment]
我试了一下，引入jquery之后确实不报错了

**Comment by pikaz-18** [comment]
> 不会吧，我没使用这个库之前没有问题，引入之后就报了这个错误

但是你可以搜索这个库，整个库都搜不到jq呀，而且这个项目几百人使用了一年多了，你搜索整个项目看看有没有地方使用了jquery，然后没引入

**Comment by xiaoawen** [comment]
你说的对，我看看，感谢大佬指点
