### ISSUE TITLE
打包体积过大

### ISSUE THREAD

**Issue by zhbittango** [pikaz-18/pikaz-excel-js#4]
打包时体积去到1.9M，请问如何处理，有提供cdn吗？

**Comment by pikaz-18** [comment]
包体积确实较大，所以我只提供了按需引入，cdn可以使用https://unpkg.com/pikaz-excel-js

**Comment by pikaz-18** [comment]
> 打包时体积去到1.9M，请问如何处理，有提供cdn吗？

包体积确实较大，所以我只提供了按需引入，cdn可以使用https://cdn.jsdelivr.net/npm/pikaz-excel-js或者https://unpkg.com/pikaz-excel-js
