### ISSUE TITLE
动态数据 修改单元格样式

### ISSUE THREAD

**Issue by HunterDestiny** [pikaz-18/pikaz-excel-js#42]
表格是动态的 如何修改表头样式 或者说怎么获取单元格名字.. 如 A1 - T1

**Comment by pikaz-18** [comment]
> 表格是动态的 如何修改表头样式 或者说怎么获取单元格名字.. 如 A1 - T1

单元格名称遵循excel的单元格名称，根据列的数量，循环遍历a到z即可，后面的数字是行数，具体的可观察excel文件，循环遍历得到单元格名称数组后，将对应样式数据组装好加入到cellStyle中即可

**Comment by HunterDestiny** [comment]
a-z 可以这样. 但是超出之后 的 aa ab bz 的就不能了吧. 没找到用列数计算出 对应表格名称的方法.

**Comment by pikaz-18** [comment]
> 表格是动态的 如何修改表头样式 或者说怎么获取单元格名字.. 如 A1 - T1



> a-z 可以这样. 但是超出之后 的 aa ab bz 的就不能了吧. 没找到用列数计算出 对应表格名称的方法.

z之后就是双字母了呀，第一个字母a，第二个字母a-z，然后第二个字母26个字母用完后，又换为b，第二个字母继续a-z，循环就行，这里六七百列足够你使用了QAQ

**Comment by HunterDestiny** [comment]
从 phpspreadsheet 这个里面找到了列数转ABCD 的方法 改成js的了
```
    /**
     * String from column index.
     * @param int columnIndex Column index (A = 1)
     * @return string
     */
    stringFromColumnIndex(columnIndex) {
      let indexCache = []
      if (!indexCache[columnIndex]) {
        let indexValue = columnIndex
        let base26 = null
        do {
          let remainder = indexValue % 26
          let characterValue = remainder ? remainder : 26
          indexValue = (indexValue - characterValue) / 26
          base26 = String.fromCharCode(characterValue + 64) + (base26 ? base26 : '')
        } while (indexValue > 0)
        indexCache[columnIndex] = base26
      }
      return indexCache[columnIndex]
    },
```

**Comment by pikaz-18** [comment]
> 从 phpspreadsheet 这个里面找到了列数转ABCD 的方法 改成js的了
> 
> ```
>     /**
>      * String from column index.
>      * @param int columnIndex Column index (A = 1)
>      * @return string
>      */
>     stringFromColumnIndex(columnIndex) {
>       let indexCache = []
>       if (!indexCache[columnIndex]) {
>         let indexValue = columnIndex
>         let base26 = null
>         do {
>           let remainder = indexValue % 26
>           let characterValue = remainder ? remainder : 26
>           indexValue = (indexValue - characterValue) / 26
>           base26 = String.fromCharCode(characterValue + 64) + (base26 ? base26 : '')
>         } while (indexValue > 0)
>         indexCache[columnIndex] = base26
>       }
>       return indexCache[columnIndex]
>     },
> ```

这个自己写个就好了呀，如果不会的话，在项目的plugin/excelExport.vue文件下，处理标题合并中的代码已经写了一个单元格列项名称获取了~~~，你可以参考一下~~~
