### ISSUE TITLE
自定义数据怎么用

### ISSUE THREAD

**Issue by 3218095895** [pikaz-18/pikaz-excel-js#47]

**Comment by pikaz-18** [comment]
> _No description provided._

可以详细说明您的问题吗

**Comment by 3218095895** [comment]
除了数据集之外，我要另起一行或多行自定义的数据放在指定位置

**Comment by 3218095895** [comment]
还有就是如何让空白数据的单元格的样式和有数据的一样，因为数据集中有空的数据，导出之后空了一块

**Comment by pikaz-18** [comment]
> 除了数据集之外，我要另起一行或多行自定义的数据放在指定位置

通过自定义keys和table，可以在任意一个单元格设置数据，keys代表列，table数组代表行

**Comment by pikaz-18** [comment]
> 还有就是如何让空白数据的单元格的样式和有数据的一样，因为数据集中有空的数据，导出之后空了一块

通过cellStyle可以给指定单元格设置样式

**Comment by 3218095895** [comment]
我可能说的不太明白，是除了数据集之外的自定义数据，
![1639109023(1)](https://user-images.githubusercontent.com/55170732/145515392-70736820-b410-46b0-a815-5f4c9b9574ed.png)

**Comment by pikaz-18** [comment]
> 我可能说的不太明白，是除了数据集之外的自定义数据， ![1639109023(1)](https://user-images.githubusercontent.com/55170732/145515392-70736820-b410-46b0-a815-5f4c9b9574ed.png)

{
          merges: ["A6:C6"],
          table: [
            {
              A: "1",
              B: "2",
              C: "3",
              D: "4",
            },
            {
              A: "5",
              B: "6",
              C: "7",
              D: "8",
            },
            {
              A: "9",
              B: "10",
              C: "11",
              D: "12",
            },
            {
              A: "",
              B: "",
              C: "",
              D: "",
            },
            {
              A: "13",
              B: "14",
              C: "15",
              D: "16",
            },
            {
              A: "合并",
              B: "",
              C: "",
              D: "",
            },
          ],
          keys: ["A", "B", "C", "D"],
          sheetName: "自定义表格",
        }
        把该对象数据加入sheet数组中，即可看到自定义格式的表格数据
