### ISSUE TITLE
如何使header文字居中，列部分左对齐，部分右对齐

### ISSUE THREAD

**Issue by Gardennias** [pikaz-18/pikaz-excel-js#48]
场景：表头文字居中，报表的文字左对齐，数字金额右对齐
只看到有一个全局设置居中方式

**Comment by pikaz-18** [comment]
> 只看到有一个全局设置居中方式

globalStyle是设置全局的，cellStyle是设置单个单元格的，你可以遍历需要设置样式的单元格去设置对应的单元格样式

**Comment by Gardennias** [comment]
> > 只看到有一个全局设置居中方式
> 
> globalStyle是设置全局的，cellStyle是设置单个单元格的，你可以遍历需要设置样式的单元格去设置对应的单元格样式 可以参考之前的两个回答：#37 #42

谢谢！！刚刚倒腾出解决方案了，
把全局 globalStyle: {alignment:{horizontal: ' '}}，设置成空格字符串，
再单独设置表头居中，下载的表格会保持html界面样式水平对齐的设置
