### ISSUE TITLE
点击之后再请求的数据，会导致点击第一次没反应，得再点击第二次才能下载

### ISSUE THREAD

**Issue by luosss** [pikaz-18/pikaz-excel-js#55]

**Comment by pikaz-18** [comment]
> _No description provided._

插件有为您提供pikaExportExcel方法，手动调起插件的导出功能，您可以在请求完数据后手动调起该方法，可以查看导出demo代码中的手动导出示例哦：https://github.com/pikaz-18/pikaz-excel-js/blob/master/src/example/components/exportDemo.vue
