### ISSUE TITLE
vue3+ts  support ?

### ISSUE THREAD

**Issue by 158710** [pikaz-18/pikaz-excel-js#58]
`vue-router.esm-bundler.js:3308 ReferenceError: cptable is not defined
    at PikazJsExcel.umd.min.js:8:92065
    at Object.<anonymous> (PikazJsExcel.umd.min.js:8:316709)
    at Object.<anonymous> (PikazJsExcel.umd.min.js:8:316716)
    at r (PikazJsExcel.umd.min.js:1:405868)
    at PikazJsExcel.umd.min.js:1:406667
    at PikazJsExcel.umd.min.js:1:406676
    at PikazJsExcel.umd.min.js:1:405729
    at 13cb (PikazJsExcel.umd.min.js:1:405732)
    at r (PikazJsExcel.umd.min.js:1:380)
    at Module.fae3 (PikazJsExcel.umd.min.js:19:38673)`

**Comment by pikaz-18** [comment]
> `vue-router.esm-bundler.js:3308 ReferenceError: cptable is not defined at PikazJsExcel.umd.min.js:8:92065 at Object.<anonymous> (PikazJsExcel.umd.min.js:8:316709) at Object.<anonymous> (PikazJsExcel.umd.min.js:8:316716) at r (PikazJsExcel.umd.min.js:1:405868) at PikazJsExcel.umd.min.js:1:406667 at PikazJsExcel.umd.min.js:1:406676 at PikazJsExcel.umd.min.js:1:405729 at 13cb (PikazJsExcel.umd.min.js:1:405732) at r (PikazJsExcel.umd.min.js:1:380) at Module.fae3 (PikazJsExcel.umd.min.js:19:38673)`

暂时还没做vue3的兼容哦~

**Comment by 785029615** [comment]
期待出vue3的版本

**Comment by pikaz-18** [comment]
> 期待出vue3的版本

新版本已支持vue3了哦

**Comment by gitLPS** [comment]
Uncaught ReferenceError: cptable is not defined，vue3+ts新项目，引入import { ExcelExport, ExcelImport } from "pikaz-excel-js";报错，能出一个vue3的教程马

**Comment by gitLPS** [comment]
Uncaught ReferenceError: cptable is not defined
    at PikazJsExcel.umd.min.js:8:92065
    at Object.<anonymous> (PikazJsExcel.umd.min.js:8:316709)
    at Object.<anonymous> (PikazJsExcel.umd.min.js:8:316716)
    at r (PikazJsExcel.umd.min.js:1:405868)
    at PikazJsExcel.umd.min.js:1:406667
    at PikazJsExcel.umd.min.js:1:406676
    at PikazJsExcel.umd.min.js:1:405729
    at 13cb (PikazJsExcel.umd.min.js:1:405732)
    at r (PikazJsExcel.umd.min.js:1:380)
    at Module.fae3 (PikazJsExcel.umd.min.js:19:38673)，
vue3+ts新项目，引入import { ExcelExport, ExcelImport } from "pikaz-excel-js";报错，能出一个vue3的教程吗，收藏这个插件好几年了，哈哈哈

**Comment by pikaz-18** [comment]
> Uncaught ReferenceError: cptable is not defined at PikazJsExcel.umd.min.js:8:92065 at Object. (PikazJsExcel.umd.min.js:8:316709) at Object. (PikazJsExcel.umd.min.js:8:316716) at r (PikazJsExcel.umd.min.js:1:405868) at PikazJsExcel.umd.min.js:1:406667 at PikazJsExcel.umd.min.js:1:406676 at PikazJsExcel.umd.min.js:1:405729 at 13cb (PikazJsExcel.umd.min.js:1:405732) at r (PikazJsExcel.umd.min.js:1:380) at Module.fae3 (PikazJsExcel.umd.min.js:19:38673)， vue3+ts新项目，引入import { ExcelExport, ExcelImport } from "pikaz-excel-js";报错，能出一个vue3的教程吗，收藏这个插件好几年了，哈哈哈

ts环境没做过测试，如果直接引入不行，可以尝试用直接文件引入，将cdn文件下载下来放到本地，然后在html中引入即可，可参考cdn的引入方式

**Comment by gitLPS** [comment]
> > Uncaught ReferenceError: cptable is not defined at PikazJsExcel.umd.min.js:8:92065 at Object. (PikazJsExcel.umd.min.js:8:316709) at Object. (PikazJsExcel.umd.min.js:8:316716) at r (PikazJsExcel.umd.min.js:1:405868) at PikazJsExcel.umd.min.js:1:406667 at PikazJsExcel.umd.min.js:1:406676 at PikazJsExcel.umd.min.js:1:405729 at 13cb (PikazJsExcel.umd.min.js:1:405732) at r (PikazJsExcel.umd.min.js:1:380) at Module.fae3 (PikazJsExcel.umd.min.js:19:38673)， vue3+ts新项目，引入import { ExcelExport, ExcelImport } from "pikaz-excel-js";报错，能出一个vue3的教程吗，收藏这个插件好几年了，哈哈哈
> 
> ts环境没做过测试，如果直接引入不行，可以尝试用直接文件引入，将cdn文件下载下来放到本地，然后在html中引入即可，可参考cdn的引入方式

我又尝试了一下正常下载，不加ts的情况下，vue3在vue cli生成架子的时候可以正常使用，但是vite生成架子时无法正常使用，很困惑，为何vite_vue3引入就报错，vue cli就不报错，

**Comment by pikaz-18** [comment]
> > > Uncaught ReferenceError: cptable is not defined at PikazJsExcel.umd.min.js:8:92065 at Object. (PikazJsExcel.umd.min.js:8:316709) at Object. (PikazJsExcel.umd.min.js:8:316716) at r (PikazJsExcel.umd.min.js:1:405868) at PikazJsExcel.umd.min.js:1:406667 at PikazJsExcel.umd.min.js:1:406676 at PikazJsExcel.umd.min.js:1:405729 at 13cb (PikazJsExcel.umd.min.js:1:405732) at r (PikazJsExcel.umd.min.js:1:380) at Module.fae3 (PikazJsExcel.umd.min.js:19:38673)， vue3+ts新项目，引入import { ExcelExport, ExcelImport } from "pikaz-excel-js";报错，能出一个vue3的教程吗，收藏这个插件好几年了，哈哈哈
> > 
> > 
> > ts环境没做过测试，如果直接引入不行，可以尝试用直接文件引入，将cdn文件下载下来放到本地，然后在html中引入即可，可参考cdn的引入方式
> 
> 我又尝试了一下正常下载，不加ts的情况下，vue3在vue cli生成架子的时候可以正常使用，但是vite生成架子时无法正常使用，很困惑，为何vite_vue3引入就报错，vue cli就不报错，

我猜测应该是vite使用的是esbuild打包，而这个插件之前用的是webpack打包，彼此之前有一定兼容性问题，vue-cli依旧使用的是webpack，所以没有这种兼容性问题

**Comment by pikaz-18** [comment]
> > > > > Uncaught ReferenceError: cptable is not defined at PikazJsExcel.umd.min.js:8:92065 at Object. (PikazJsExcel.umd.min.js:8:316709) at Object. (PikazJsExcel.umd.min.js:8:316716) at r (PikazJsExcel.umd.min.js:1:405868) at PikazJsExcel.umd.min.js:1:406667 at PikazJsExcel.umd.min.js:1:406676 at PikazJsExcel.umd.min.js:1:405729 at 13cb (PikazJsExcel.umd.min.js:1:405732) at r (PikazJsExcel.umd.min.js:1:380) at Module.fae3 (PikazJsExcel.umd.min.js:19:38673)， vue3+ts新项目，引入import { ExcelExport, ExcelImport } from "pikaz-excel-js";报错，能出一个vue3的教程吗，收藏这个插件好几年了，哈哈哈
> > > > 
> > > > 
> > > > ts环境没做过测试，如果直接引入不行，可以尝试用直接文件引入，将cdn文件下载下来放到本地，然后在html中引入即可，可参考cdn的引入方式
> > > 
> > > 
> > > 我又尝试了一下正常下载，不加ts的情况下，vue3在vue cli生成架子的时候可以正常使用，但是vite生成架子时无法正常使用，很困惑，为何vite_vue3引入就报错，vue cli就不报错，
> > 
> > 
> > 我猜测应该是vite使用的是esbuild打包，而这个插件之前用的是webpack打包，彼此之前有一定兼容性问题，vue-cli依旧使用的是webpack，所以没有这种兼容性问题
> 
> 期待兼容vite❤❤❤

实在没有精力了，如果可以使用cdn式的文件引入的方式使用的话就先这样用吧，我最近也要失业了，要找工作QAQ

**Comment by gitLPS** [comment]
> > > > > > Uncaught ReferenceError: cptable is not defined at PikazJsExcel.umd.min.js:8:92065 at Object. (PikazJsExcel.umd.min.js:8:316709) at Object. (PikazJsExcel.umd.min.js:8:316716) at r (PikazJsExcel.umd.min.js:1:405868) at PikazJsExcel.umd.min.js:1:406667 at PikazJsExcel.umd.min.js:1:406676 at PikazJsExcel.umd.min.js:1:405729 at 13cb (PikazJsExcel.umd.min.js:1:405732) at r (PikazJsExcel.umd.min.js:1:380) at Module.fae3 (PikazJsExcel.umd.min.js:19:38673)， vue3+ts新项目，引入import { ExcelExport, ExcelImport } from "pikaz-excel-js";报错，能出一个vue3的教程吗，收藏这个插件好几年了，哈哈哈
> > > > > 
> > > > > 
> > > > > ts环境没做过测试，如果直接引入不行，可以尝试用直接文件引入，将cdn文件下载下来放到本地，然后在html中引入即可，可参考cdn的引入方式
> > > > 
> > > > 
> > > > 我又尝试了一下正常下载，不加ts的情况下，vue3在vue cli生成架子的时候可以正常使用，但是vite生成架子时无法正常使用，很困惑，为何vite_vue3引入就报错，vue cli就不报错，
> > > 
> > > 
> > > 我猜测应该是vite使用的是esbuild打包，而这个插件之前用的是webpack打包，彼此之前有一定兼容性问题，vue-cli依旧使用的是webpack，所以没有这种兼容性问题
> > 
> > 
> > 期待兼容vite❤❤❤
> 
> 实在没有精力了，如果可以使用cdn式的文件引入的方式使用的话就先这样用吧，我最近也要失业了，要找工作QAQ

加油✊✊✊

**Comment by gitLPS** [comment]
建议导入的时候，可以多解析一个tHeader，目前导入只接了数据，获取表头我用的object.keys(data[0]),如果该行数据不完整，则会导致 表头取不出来，大佬有什么方案吗
