### ISSUE TITLE
table数据中不能有Number类型!

### ISSUE THREAD

**Issue by Supan1989** [pikaz-18/pikaz-excel-js#6]
[
{
"title":"费用科目统计(按科室)",
"tHeader":[
"科室名称",
"总费用"
],
"table":[
{
"DeptName":"全科2（儿）",
"TotalCost":33809.09
},
{
"DeptName":"东吴全科",
"TotalCost":8542.36
},
{
"DeptName":"产前检查门诊",
"TotalCost":5508.03
},
{
"DeptName":"早孕产后门诊",
"TotalCost":2221.21
},
{
"DeptName":"中医专科",
"TotalCost":58709.28
},
{
"DeptName":"全科3（外）",
"TotalCost":93162.26
},
{
"DeptName":"儿童保健科",
"TotalCost":5372.41
},
{
"DeptName":"牟山湖全科",
"TotalCost":2973.42
},
{
"DeptName":"妇科专家",
"TotalCost":4482.04
},
{
"DeptName":"全科1（内）",
"TotalCost":334884.32
},
{
"DeptName":"狮山全科",
"TotalCost":16557.87
},
{
"DeptName":"胡家全科",
"TotalCost":2235.29
},
{
"DeptName":"口腔科专家",
"TotalCost":2083.36
},
{
"DeptName":"湖山全科",
"TotalCost":8377.7
},
{
"DeptName":"魏家全科",
"TotalCost":2964.42
},
{
"DeptName":"妇科普通",
"TotalCost":1498.22
},
{
"DeptName":"陈家全科",
"TotalCost":113.93
},
{
"DeptName":"口腔科",
"TotalCost":19749.27
},
{
"DeptName":"专家门诊",
"TotalCost":12048.23
},
{
"DeptName":"防保科",
"TotalCost":69872.9
},
{
"DeptName":"妇科门诊",
"TotalCost":33377.49
}
],
"keys":[
"DeptName",
"TotalCost"
],
"sheetName":"表1-费用科目统计(按科室)",
"cellStyle":[
{
"cell":"A1",
"font":{
"sz":14,
"color":{
"rgb":"ffffff"
},
"bold":true
}
}
]
}
]
报错
vue.runtime.esm.js:619 [Vue warn]: Error in nextTick: "TypeError: t.split is not a function"

found in

---> <ExcelExport>
       <FeeItemReportTable> at src/views/feeItem/components/ReportTable/index.vue
         <ElCard> at packages/card/src/main.vue
           <ElCol>
             <ElRow>
               <StandardTablePage> at jq_modules/templates/StandardTablePage.vue
                 <FeeItem> at src/views/feeItem/index.vue
                   <AppMain> at src/layouts/components/AppMain/index.vue
                     <Layout> at src/layouts/Layout.vue
                       <App> at src/App.vue
                         <Root>

---------------
table中的数据必须为String 如果是Number 无法.split()
--------------

**Comment by pikaz-18** [comment]
> [
> {
> "title":"费用科目统计(按科室)",
> "tHeader":[
> "科室名称",
> "总费用"
> ],
> "table":[
> {
> "DeptName":"全科2（儿）",
> "TotalCost":33809.09
> },
> {
> "DeptName":"东吴全科",
> "TotalCost":8542.36
> },
> {
> "DeptName":"产前检查门诊",
> "TotalCost":5508.03
> },
> {
> "DeptName":"早孕产后门诊",
> "TotalCost":2221.21
> },
> {
> "DeptName":"中医专科",
> "TotalCost":58709.28
> },
> {
> "DeptName":"全科3（外）",
> "TotalCost":93162.26
> },
> {
> "DeptName":"儿童保健科",
> "TotalCost":5372.41
> },
> {
> "DeptName":"牟山湖全科",
> "TotalCost":2973.42
> },
> {
> "DeptName":"妇科专家",
> "TotalCost":4482.04
> },
> {
> "DeptName":"全科1（内）",
> "TotalCost":334884.32
> },
> {
> "DeptName":"狮山全科",
> "TotalCost":16557.87
> },
> {
> "DeptName":"胡家全科",
> "TotalCost":2235.29
> },
> {
> "DeptName":"口腔科专家",
> "TotalCost":2083.36
> },
> {
> "DeptName":"湖山全科",
> "TotalCost":8377.7
> },
> {
> "DeptName":"魏家全科",
> "TotalCost":2964.42
> },
> {
> "DeptName":"妇科普通",
> "TotalCost":1498.22
> },
> {
> "DeptName":"陈家全科",
> "TotalCost":113.93
> },
> {
> "DeptName":"口腔科",
> "TotalCost":19749.27
> },
> {
> "DeptName":"专家门诊",
> "TotalCost":12048.23
> },
> {
> "DeptName":"防保科",
> "TotalCost":69872.9
> },
> {
> "DeptName":"妇科门诊",
> "TotalCost":33377.49
> }
> ],
> "keys":[
> "DeptName",
> "TotalCost"
> ],
> "sheetName":"表1-费用科目统计(按科室)",
> "cellStyle":[
> {
> "cell":"A1",
> "font":{
> "sz":14,
> "color":{
> "rgb":"ffffff"
> },
> "bold":true
> }
> }
> ]
> }
> ]
> 报错
> vue.runtime.esm.js:619 [Vue warn]: Error in nextTick: "TypeError: t.split is not a function"
> 
> found in
> 
> --->
> at src/views/feeItem/components/ReportTable/index.vue
> at packages/card/src/main.vue
> 
> 
> at jq_modules/templates/StandardTablePage.vue
> at src/views/feeItem/index.vue
> at src/layouts/components/AppMain/index.vue
> at src/layouts/Layout.vue
> at src/App.vue
> ## table中的数据必须为String 如果是Number 无法.split()

如果需要使用自动列宽，请将所有数据类型更改为字符串，如需保留数据类型，请手动设置列宽colWidth，等会我更改一下文档说明，这个漏了。

**Comment by Supan1989** [comment]
恩 谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "pikaz"<notifications@github.com&gt;; 
发送时间: 2020年7月13日(星期一) 中午1:52
收件人: "pikaz-18/pikaz-excel-js"<pikaz-excel-js@noreply.github.com&gt;; 
抄送: "woaini"<740736297@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pikaz-18/pikaz-excel-js] table数据中不能有Number类型! (#6)





  
[
 {
 "title":"费用科目统计(按科室)",
 "tHeader":[
 "科室名称",
 "总费用"
 ],
 "table":[
 {
 "DeptName":"全科2（儿）",
 "TotalCost":33809.09
 },
 {
 "DeptName":"东吴全科",
 "TotalCost":8542.36
 },
 {
 "DeptName":"产前检查门诊",
 "TotalCost":5508.03
 },
 {
 "DeptName":"早孕产后门诊",
 "TotalCost":2221.21
 },
 {
 "DeptName":"中医专科",
 "TotalCost":58709.28
 },
 {
 "DeptName":"全科3（外）",
 "TotalCost":93162.26
 },
 {
 "DeptName":"儿童保健科",
 "TotalCost":5372.41
 },
 {
 "DeptName":"牟山湖全科",
 "TotalCost":2973.42
 },
 {
 "DeptName":"妇科专家",
 "TotalCost":4482.04
 },
 {
 "DeptName":"全科1（内）",
 "TotalCost":334884.32
 },
 {
 "DeptName":"狮山全科",
 "TotalCost":16557.87
 },
 {
 "DeptName":"胡家全科",
 "TotalCost":2235.29
 },
 {
 "DeptName":"口腔科专家",
 "TotalCost":2083.36
 },
 {
 "DeptName":"湖山全科",
 "TotalCost":8377.7
 },
 {
 "DeptName":"魏家全科",
 "TotalCost":2964.42
 },
 {
 "DeptName":"妇科普通",
 "TotalCost":1498.22
 },
 {
 "DeptName":"陈家全科",
 "TotalCost":113.93
 },
 {
 "DeptName":"口腔科",
 "TotalCost":19749.27
 },
 {
 "DeptName":"专家门诊",
 "TotalCost":12048.23
 },
 {
 "DeptName":"防保科",
 "TotalCost":69872.9
 },
 {
 "DeptName":"妇科门诊",
 "TotalCost":33377.49
 }
 ],
 "keys":[
 "DeptName",
 "TotalCost"
 ],
 "sheetName":"表1-费用科目统计(按科室)",
 "cellStyle":[
 {
 "cell":"A1",
 "font":{
 "sz":14,
 "color":{
 "rgb":"ffffff"
 },
 "bold":true
 }
 }
 ]
 }
 ]
 报错
 vue.runtime.esm.js:619 [Vue warn]: Error in nextTick: "TypeError: t.split is not a function"
 
found in
 
---&gt;
 at src/views/feeItem/components/ReportTable/index.vue
 at packages/card/src/main.vue
 
at jq_modules/templates/StandardTablePage.vue
 at src/views/feeItem/index.vue
 at src/layouts/components/AppMain/index.vue
 at src/layouts/Layout.vue
 at src/App.vue
 
table中的数据必须为String 如果是Number 无法.split()
  
如果需要使用自动列宽，请将所有数据类型更改为字符串，如需保留数据类型，请手动设置列宽colWidth，等会我更改一下文档说明，这个漏了。

**Comment by Supan1989** [comment]
大佬 merge的单元格样式怎么写




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "pikaz"<notifications@github.com&gt;; 
发送时间: 2020年7月13日(星期一) 中午1:52
收件人: "pikaz-18/pikaz-excel-js"<pikaz-excel-js@noreply.github.com&gt;; 
抄送: "woaini"<740736297@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pikaz-18/pikaz-excel-js] table数据中不能有Number类型! (#6)





  
[
 {
 "title":"费用科目统计(按科室)",
 "tHeader":[
 "科室名称",
 "总费用"
 ],
 "table":[
 {
 "DeptName":"全科2（儿）",
 "TotalCost":33809.09
 },
 {
 "DeptName":"东吴全科",
 "TotalCost":8542.36
 },
 {
 "DeptName":"产前检查门诊",
 "TotalCost":5508.03
 },
 {
 "DeptName":"早孕产后门诊",
 "TotalCost":2221.21
 },
 {
 "DeptName":"中医专科",
 "TotalCost":58709.28
 },
 {
 "DeptName":"全科3（外）",
 "TotalCost":93162.26
 },
 {
 "DeptName":"儿童保健科",
 "TotalCost":5372.41
 },
 {
 "DeptName":"牟山湖全科",
 "TotalCost":2973.42
 },
 {
 "DeptName":"妇科专家",
 "TotalCost":4482.04
 },
 {
 "DeptName":"全科1（内）",
 "TotalCost":334884.32
 },
 {
 "DeptName":"狮山全科",
 "TotalCost":16557.87
 },
 {
 "DeptName":"胡家全科",
 "TotalCost":2235.29
 },
 {
 "DeptName":"口腔科专家",
 "TotalCost":2083.36
 },
 {
 "DeptName":"湖山全科",
 "TotalCost":8377.7
 },
 {
 "DeptName":"魏家全科",
 "TotalCost":2964.42
 },
 {
 "DeptName":"妇科普通",
 "TotalCost":1498.22
 },
 {
 "DeptName":"陈家全科",
 "TotalCost":113.93
 },
 {
 "DeptName":"口腔科",
 "TotalCost":19749.27
 },
 {
 "DeptName":"专家门诊",
 "TotalCost":12048.23
 },
 {
 "DeptName":"防保科",
 "TotalCost":69872.9
 },
 {
 "DeptName":"妇科门诊",
 "TotalCost":33377.49
 }
 ],
 "keys":[
 "DeptName",
 "TotalCost"
 ],
 "sheetName":"表1-费用科目统计(按科室)",
 "cellStyle":[
 {
 "cell":"A1",
 "font":{
 "sz":14,
 "color":{
 "rgb":"ffffff"
 },
 "bold":true
 }
 }
 ]
 }
 ]
 报错
 vue.runtime.esm.js:619 [Vue warn]: Error in nextTick: "TypeError: t.split is not a function"
 
found in
 
---&gt;
 at src/views/feeItem/components/ReportTable/index.vue
 at packages/card/src/main.vue
 
at jq_modules/templates/StandardTablePage.vue
 at src/views/feeItem/index.vue
 at src/layouts/components/AppMain/index.vue
 at src/layouts/Layout.vue
 at src/App.vue
 
table中的数据必须为String 如果是Number 无法.split()
  
如果需要使用自动列宽，请将所有数据类型更改为字符串，如需保留数据类型，请手动设置列宽colWidth，等会我更改一下文档说明，这个漏了。

**Comment by pikaz-18** [comment]
> 大佬 merge的单元格样式怎么写
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "pikaz"<notifications@github.com&gt;; 发送时间: 2020年7月13日(星期一) 中午1:52 收件人: "pikaz-18/pikaz-excel-js"<pikaz-excel-js@noreply.github.com&gt;; 抄送: "woaini"<740736297@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [pikaz-18/pikaz-excel-js] table数据中不能有Number类型! (#6) [ { "title":"费用科目统计(按科室)", "tHeader":[ "科室名称", "总费用" ], "table":[ { "DeptName":"全科2（儿）", "TotalCost":33809.09 }, { "DeptName":"东吴全科", "TotalCost":8542.36 }, { "DeptName":"产前检查门诊", "TotalCost":5508.03 }, { "DeptName":"早孕产后门诊", "TotalCost":2221.21 }, { "DeptName":"中医专科", "TotalCost":58709.28 }, { "DeptName":"全科3（外）", "TotalCost":93162.26 }, { "DeptName":"儿童保健科", "TotalCost":5372.41 }, { "DeptName":"牟山湖全科", "TotalCost":2973.42 }, { "DeptName":"妇科专家", "TotalCost":4482.04 }, { "DeptName":"全科1（内）", "TotalCost":334884.32 }, { "DeptName":"狮山全科", "TotalCost":16557.87 }, { "DeptName":"胡家全科", "TotalCost":2235.29 }, { "DeptName":"口腔科专家", "TotalCost":2083.36 }, { "DeptName":"湖山全科", "TotalCost":8377.7 }, { "DeptName":"魏家全科", "TotalCost":2964.42 }, { "DeptName":"妇科普通", "TotalCost":1498.22 }, { "DeptName":"陈家全科", "TotalCost":113.93 }, { "DeptName":"口腔科", "TotalCost":19749.27 }, { "DeptName":"专家门诊", "TotalCost":12048.23 }, { "DeptName":"防保科", "TotalCost":69872.9 }, { "DeptName":"妇科门诊", "TotalCost":33377.49 } ], "keys":[ "DeptName", "TotalCost" ], "sheetName":"表1-费用科目统计(按科室)", "cellStyle":[ { "cell":"A1", "font":{ "sz":14, "color":{ "rgb":"ffffff" }, "bold":true } } ] } ] 报错 vue.runtime.esm.js:619 [Vue warn]: Error in nextTick: "TypeError: t.split is not a function" found in
> ---&gt; at src/views/feeItem/components/ReportTable/index.vue at packages/card/src/main.vue at jq_modules/templates/StandardTablePage.vue at src/views/feeItem/index.vue at src/layouts/components/AppMain/index.vue at src/layouts/Layout.vue at src/App.vue table中的数据必须为String 如果是Number 无法.split() 如果需要使用自动列宽，请将所有数据类型更改为字符串，如需保留数据类型，请手动设置列宽colWidth，等会我更改一下文档说明，这个漏了。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可以参考demo代码中的exportdemo代码以及文档，比如你要合并A2-C2单元格，里面信息为"合并单元格"，那么A2单元格对应的数据"合并单元格"，B2和C2单元格对应的数据写空字符串，并加入合并配置merge:['A2:C2']

**Comment by Supan1989** [comment]
恩 已经get到了&nbsp; 现在主要问题是合并单元格以后会把第一格撑开，而且设置了换行 没地方设置单元格高度




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "pikaz"<notifications@github.com&gt;; 
发送时间: 2020年7月14日(星期二) 中午12:01
收件人: "pikaz-18/pikaz-excel-js"<pikaz-excel-js@noreply.github.com&gt;; 
抄送: "woaini"<740736297@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pikaz-18/pikaz-excel-js] table数据中不能有Number类型! (#6)





  
大佬 merge的单元格样式怎么写
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "pikaz"<notifications@github.com&gt;; 发送时间: 2020年7月13日(星期一) 中午1:52 收件人: "pikaz-18/pikaz-excel-js"<pikaz-excel-js@noreply.github.com&gt;; 抄送: "woaini"<740736297@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [pikaz-18/pikaz-excel-js] table数据中不能有Number类型! (#6) [ { "title":"费用科目统计(按科室)", "tHeader":[ "科室名称", "总费用" ], "table":[ { "DeptName":"全科2（儿）", "TotalCost":33809.09 }, { "DeptName":"东吴全科", "TotalCost":8542.36 }, { "DeptName":"产前检查门诊", "TotalCost":5508.03 }, { "DeptName":"早孕产后门诊", "TotalCost":2221.21 }, { "DeptName":"中医专科", "TotalCost":58709.28 }, { "DeptName":"全科3（外）", "TotalCost":93162.26 }, { "DeptName":"儿童保健科", "TotalCost":5372.41 }, { "DeptName":"牟山湖全科", "TotalCost":2973.42 }, { "DeptName":"妇科专家", "TotalCost":4482.04 }, { "DeptName":"全科1（内）", "TotalCost":334884.32 }, { "DeptName":"狮山全科", "TotalCost":16557.87 }, { "DeptName":"胡家全科", "TotalCost":2235.29 }, { "DeptName":"口腔科专家", "TotalCost":2083.36 }, { "DeptName":"湖山全科", "TotalCost":8377.7 }, { "DeptName":"魏家全科", "TotalCost":2964.42 }, { "DeptName":"妇科普通", "TotalCost":1498.22 }, { "DeptName":"陈家全科", "TotalCost":113.93 }, { "DeptName":"口腔科", "TotalCost":19749.27 }, { "DeptName":"专家门诊", "TotalCost":12048.23 }, { "DeptName":"防保科", "TotalCost":69872.9 }, { "DeptName":"妇科门诊", "TotalCost":33377.49 } ], "keys":[ "DeptName", "TotalCost" ], "sheetName":"表1-费用科目统计(按科室)", "cellStyle":[ { "cell":"A1", "font":{ "sz":14, "color":{ "rgb":"ffffff" }, "bold":true } } ] } ] 报错 vue.runtime.esm.js:619 [Vue warn]: Error in nextTick: "TypeError: t.split is not a function" found in
 ---&gt; at src/views/feeItem/components/ReportTable/index.vue at packages/card/src/main.vue at jq_modules/templates/StandardTablePage.vue at src/views/feeItem/index.vue at src/layouts/components/AppMain/index.vue at src/layouts/Layout.vue at src/App.vue table中的数据必须为String 如果是Number 无法.split() 如果需要使用自动列宽，请将所有数据类型更改为字符串，如需保留数据类型，请手动设置列宽colWidth，等会我更改一下文档说明，这个漏了。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
可以参考demo代码中的exportdemo代码以及文档，比如你要合并A2-C2单元格，里面信息为"合并单元格"，那么A2单元格对应的数据"合并单元格"，B2和C2单元格对应的数据写空字符串，并加入合并配置merge:['A2:C2']

**Comment by pikaz-18** [comment]
> 恩 已经get到了&nbsp; 现在主要问题是合并单元格以后会把第一格撑开，而且设置了换行 没地方设置单元格高度
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "pikaz"<notifications@github.com&gt;; 发送时间: 2020年7月14日(星期二) 中午12:01 收件人: "pikaz-18/pikaz-excel-js"<pikaz-excel-js@noreply.github.com&gt;; 抄送: "woaini"<740736297@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [pikaz-18/pikaz-excel-js] table数据中不能有Number类型! (#6) 大佬 merge的单元格样式怎么写 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "pikaz"<notifications@github.com&gt;; 发送时间: 2020年7月13日(星期一) 中午1:52 收件人: "pikaz-18/pikaz-excel-js"<pikaz-excel-js@noreply.github.com&gt;; 抄送: "woaini"<740736297@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [pikaz-18/pikaz-excel-js] table数据中不能有Number类型! (#6) [ { "title":"费用科目统计(按科室)", "tHeader":[ "科室名称", "总费用" ], "table":[ { "DeptName":"全科2（儿）", "TotalCost":33809.09 }, { "DeptName":"东吴全科", "TotalCost":8542.36 }, { "DeptName":"产前检查门诊", "TotalCost":5508.03 }, { "DeptName":"早孕产后门诊", "TotalCost":2221.21 }, { "DeptName":"中医专科", "TotalCost":58709.28 }, { "DeptName":"全科3（外）", "TotalCost":93162.26 }, { "DeptName":"儿童保健科", "TotalCost":5372.41 }, { "DeptName":"牟山湖全科", "TotalCost":2973.42 }, { "DeptName":"妇科专家", "TotalCost":4482.04 }, { "DeptName":"全科1（内）", "TotalCost":334884.32 }, { "DeptName":"狮山全科", "TotalCost":16557.87 }, { "DeptName":"胡家全科", "TotalCost":2235.29 }, { "DeptName":"口腔科专家", "TotalCost":2083.36 }, { "DeptName":"湖山全科", "TotalCost":8377.7 }, { "DeptName":"魏家全科", "TotalCost":2964.42 }, { "DeptName":"妇科普通", "TotalCost":1498.22 }, { "DeptName":"陈家全科", "TotalCost":113.93 }, { "DeptName":"口腔科", "TotalCost":19749.27 }, { "DeptName":"专家门诊", "TotalCost":12048.23 }, { "DeptName":"防保科", "TotalCost":69872.9 }, { "DeptName":"妇科门诊", "TotalCost":33377.49 } ], "keys":[ "DeptName", "TotalCost" ], "sheetName":"表1-费用科目统计(按科室)", "cellStyle":[ { "cell":"A1", "font":{ "sz":14, "color":{ "rgb":"ffffff" }, "bold":true } } ] } ] 报错 vue.runtime.esm.js:619 [Vue warn]: Error in nextTick: "TypeError: t.split is not a function" found in ---&gt; at src/views/feeItem/components/ReportTable/index.vue at packages/card/src/main.vue at jq_modules/templates/StandardTablePage.vue at src/views/feeItem/index.vue at src/layouts/components/AppMain/index.vue at src/layouts/Layout.vue at src/App.vue table中的数据必须为String 如果是Number 无法.split() 如果需要使用自动列宽，请将所有数据类型更改为字符串，如需保留数据类型，请手动设置列宽colWidth，等会我更改一下文档说明，这个漏了。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 可以参考demo代码中的exportdemo代码以及文档，比如你要合并A2-C2单元格，里面信息为"合并单元格"，那么A2单元格对应的数据"合并单元格"，B2和C2单元格对应的数据写空字符串，并加入合并配置merge:['A2:C2'] — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

具体想要的样式可以说一下吗
