### ISSUE TITLE
vue-cli3中能不能按需引入？包体积实在太大

### ISSUE THREAD

**Issue by Evecang** [pikaz-18/pikaz-excel-js#64]

**Comment by pikaz-18** [comment]
> _No description provided._

vue-cli使用webpack构建，webpack默认有treeshaking，只要你import引入对应的导入或者导出库，构建时会自动把未引入的部分排除在打包内容之外的，如果觉得项目打包体积太大，也可以使用cdn的方式引入

**Comment by Evecang** [comment]
好的谢谢~
实测CDN方式使用jsdelivr引入时，响应速度不稳定，有时候超10s

**Comment by pikaz-18** [comment]
> 好的谢谢~ 实测CDN方式使用jsdelivr引入时，响应速度不稳定，有时候超10s

那就直接安装npm依赖吧，webpack打包会摇树和压缩的，体积其实还好

**Comment by Evecang** [comment]
嗯谢谢
