### ISSUE TITLE
建议：导入模板的时候建议增加几个钩子函数

### ISSUE THREAD

**Issue by zhanghaifei1997** [pikaz-18/pikaz-excel-js#65]
导入模板的时候建议释放开（看下面），因为有的时候我把模板导进来数据还要进行二次处理，页面反应时间挺长的，先加一个loading都没法加，因为需要判断什么时候开始导入什么时候导入结束。
before-import|文件导入前的钩子，参数file为导入文件|function(file)|--|--
on-progress|文件导入时的钩子|function(event,file)|--|--
on-change|文件状态改变时的钩子，导入文件、导入成功和导入失败时都会被调用|function(file)|--|--
on-success|文件导入成功的钩子，参数response为生成的json数据|function(response, file)|--|--
on-error|文件导入失败的钩子，参数error为错误信息|function(error, file)|--|--

**Comment by pikaz-18** [comment]
导入是有钩子的哦，注意看最底下import组件的参数

**Comment by pikaz-18** [comment]
> 导入模板的时候建议释放开（看下面），因为有的时候我把模板导进来数据还要进行二次处理，页面反应时间挺长的，先加一个loading都没法加，因为需要判断什么时候开始导入什么时候导入结束。 before-import|文件导入前的钩子，参数file为导入文件|function(file)|--|-- on-progress|文件导入时的钩子|function(event,file)|--|-- on-change|文件状态改变时的钩子，导入文件、导入成功和导入失败时都会被调用|function(file)|--|-- on-success|文件导入成功的钩子，参数response为生成的json数据|function(response, file)|--|-- on-error|文件导入失败的钩子，参数error为错误信息|function(error, file)|--|--

导入是有钩子的哦，注意看最底下import组件的参数
