### ISSUE TITLE
导出的文件单元格支持下拉框吗

### ISSUE THREAD

**Issue by feedoom** [pikaz-18/pikaz-excel-js#67]
![屏幕截图 2023-01-05 104506](https://user-images.githubusercontent.com/37018475/210696051-12bbe328-d284-4733-a13d-105602871d8a.png)
像这样

**Comment by pikaz-18** [comment]
> ![屏幕截图 2023-01-05 104506](https://user-images.githubusercontent.com/37018475/210696051-12bbe328-d284-4733-a13d-105602871d8a.png) 像这样

暂不支持
