### ISSUE TITLE
请问在最新版本中配置项 multiHeader 不在了  那么设置多级表头功能应该如何实现呢

### ISSUE THREAD

**Issue by py-xzczc** [pikaz-18/pikaz-excel-js#69]

**Comment by pikaz-18** [comment]
> _No description provided._

可以使用table与keys实现，这两个实际就是定义行与列，新版本去掉multiHeader就是考虑到这个配置有点多余了
自定义表格效果可以参考demo示例中导出excel的表2：
![image](https://user-images.githubusercontent.com/44502383/224893885-d3596107-cae2-4e99-bb06-37384fee9996.png)
文档中也有代码可供copy

**Comment by py-xzczc** [comment]
好的 谢谢
