### ISSUE TITLE
colWidth 无效

### ISSUE THREAD

**Issue by dadaguai-git** [pikaz-18/pikaz-excel-js#71]
我在**sheet**里 设置 **colWidth：100** 但是直接报错

错误代码：
**Uncaught (in promise) TypeError: c.map is not a function
    at pikaz-excel-js?_=1680327654883:2:1818288
    at Array.forEach (<anonymous>)
    at h (pikaz-excel-js?_=1680327654883:2:1817047)**

求解决

**Comment by pikaz-18** [comment]
> 我在**sheet**里 设置 **colWidth：100** 但是直接报错
> 
> 错误代码： **Uncaught (in promise) TypeError: c.map is not a function at pikaz-excel-js?_=1680327654883:2:1818288 at Array.forEach () at h (pikaz-excel-js?_=1680327654883:2:1817047)**
> 
> 求解决

尝试了下并没有问题，注意一下colWidth标注的类型，是数字数组哦
