### ISSUE TITLE
新版怎么让表格全局样式的背景色改成无填充颜色，现在默认是白色，。。？

### ISSUE THREAD

**Issue by LiuYangoo** [pikaz-18/pikaz-excel-js#72]
新版怎么让表格全局样式的背景色改成无填充颜色，现在默认是白色，。。？
![image](https://user-images.githubusercontent.com/24427538/230260078-1bd871f2-aa5a-4578-8aa3-6587c9c22903.png)

![Uploading image.png…]()

**Comment by pikaz-18** [comment]
全局样式中有一个填充背景色fill属性，可以将它改为你需要的背景色

**Comment by LiuYangoo** [comment]
fill: { fgColor: { { rgb: "ffffff" } }   这个属性我看到了，现在我不想设置背景色，想设置成无填充颜色 怎么设置呢？像下面的效果
![image](https://user-images.githubusercontent.com/24427538/230274330-832fc7cf-ed96-4641-aec0-d3742b483dca.png)

**Comment by pikaz-18** [comment]
> 

目前不支持，必须要设置一个背景色，默认设置是白色

**Comment by pikaz-18** [comment]
> fill: { fgColor: { { rgb: "ffffff" } } 这个属性我看到了，现在我不想设置背景色，想设置成无填充颜色 怎么设置呢？像下面的效果 ![image](https://user-images.githubusercontent.com/24427538/230274330-832fc7cf-ed96-4641-aec0-d3742b483dca.png)

目前不支持，必须要设置一个背景色，默认设置是白色

**Comment by LiuYangoo** [comment]
好吧。。
