### ISSUE TITLE
ReferenceError: cptable is not defined

### ISSUE THREAD

**Issue by yuhaowen0917** [pikaz-18/pikaz-excel-js#76]
在vue3中导入
import { excelExport } from "pikaz-excel-js";
报错：ReferenceError: cptable is not defined
求助如何解决

**Comment by pikaz-18** [comment]
> 在vue3中导入 import { excelExport } from "pikaz-excel-js"; 报错：ReferenceError: cptable is not defined 求助如何解决

使用的版本是什么？最新版本吗

**Comment by pikaz-18** [comment]
> 在vue3中导入 import { excelExport } from "pikaz-excel-js"; 报错：ReferenceError: cptable is not defined 求助如何解决

如果是使用ts、vite，可以参考这个回答：https://github.com/pikaz-18/pikaz-excel-js/issues/58；用cdn的方式引入
