### ISSUE TITLE
vue3无法导出：cptable is not defined

### ISSUE THREAD

**Issue by yuejingchuan** [pikaz-18/pikaz-excel-js#79]
![7e6e8f92-d04f-49ea-a544-27954ebe0213](https://github.com/user-attachments/assets/5eaf6277-2c71-4c4b-95d9-de1c9e6e2058)
萌新提问，vue3点击事件触发excelExport的时候，会报错
请问如何解决呢？

**Comment by pikaz-18** [comment]
请使用cdn方式引入（也可以将cdn文件直接下载到项目当中引入），目前该库还没有发布esmodule版本，之前用的webpack打包，没法兼容vue3的vite打包工具，预计12月底会发布新版本

**Comment by pikaz-18** [comment]
> 请使用cdn方式引入（也可以将cdn文件直接下载到项目当中引入），目前该库还没有发布esmodule版本，之前用的webpack打包，没法兼容vue3的vite打包工具，预计12月底会发布新版本

请使用cdn方式引入（也可以将cdn文件直接下载到项目当中引入），目前该库还没有发布esmodule版本，之前用的webpack打包，没法兼容vue3的vite打包工具，预计12月底会发布新版本

**Comment by yuejingchuan** [comment]
好的，希望大佬能尽快更新vue3 vite版本的！
