### ISSUE TITLE
行数据太多。sheet[0].title 不居中

### ISSUE THREAD

**Issue by yang317621308** [pikaz-18/pikaz-excel-js#8]
行数据中，列超过26个字母后，title为左对齐并且列未合并

>

**Comment by pikaz-18** [comment]
> 行数据中，列超过26个字母后，title为左对齐并且列未合并
> 
> >

可以给一份测试数据吗

**Comment by yang317621308** [comment]
大佬，能加我wx吗？ 317621308，数据无法给你。政府数据，理解一下。

**Comment by pikaz-18** [comment]
> 大佬，能加我wx吗？ 317621308，数据无法给你。政府数据，理解一下。

已修复

**Comment by yang317621308** [comment]
今天发现 1.0.0版本出现组件无法注册情况，望处理下，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pikaz-18/pikaz-excel-js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2020年7月24日(星期五) 上午9:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pikaz-18/pikaz-excel-js] 行数据太多。sheet[0].title 不居中 (#8)





  
行数据中，列超过26个字母后，title为左对齐并且列未合并
    
可以给一份测试数据吗

**Comment by pikaz-18** [comment]
> 今天发现 1.0.0版本出现组件无法注册情况，望处理下，谢谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "pikaz-18/pikaz-excel-js" ***@***.***&gt;; 发送时间:&nbsp;2020年7月24日(星期五) 上午9:25 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [pikaz-18/pikaz-excel-js] 行数据太多。sheet[0].title 不居中 (#8) 行数据中，列超过26个字母后，title为左对齐并且列未合并 可以给一份测试数据吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

注意版本哦，1.00版本已经改为纯js插件了，可以应用在vue3中，如果想使用旧版本不要升级，版本用回0.2.16

**Comment by yang317621308** [comment]
import {ExcelExport} from 'pikaz-excel-js'   ...   export default {         components: {             ExcelExport,         },         data () {           return {             sheet:[               {                 title:"水果的味道",                 tHeader:["荔枝","柠檬"],                 table:[{litchi:"甜",lemon:"酸"}],                 keys:["litchi","lemon"],                 sheetName:"水果的味道"               }             ]           }         }


使用的这个示例。第一行

这个如何去掉。使用的 0.2版本，希望您能尽快回复下。谢谢




清风小阳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "清风小阳"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月26日(星期五) 晚上6:01
***@***.***&gt;;

主题:&nbsp;回复： [pikaz-18/pikaz-excel-js] 行数据太多。sheet[0].title 不居中 (#8)





今天发现 1.0.0版本出现组件无法注册情况，望处理下，谢谢


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "pikaz-18/pikaz-excel-js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2020年7月24日(星期五) 上午9:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pikaz-18/pikaz-excel-js] 行数据太多。sheet[0].title 不居中 (#8)





  
行数据中，列超过26个字母后，title为左对齐并且列未合并
    
可以给一份测试数据吗

**Comment by pikaz-18** [comment]
> 

第一行指的是标题吗，如果是标题，只要去掉title即可

**Comment by pikaz-18** [comment]
> import {ExcelExport} from 'pikaz-excel-js' ... export default { components: { ExcelExport, }, data () { return { sheet:[ { title:"水果的味道", tHeader:["荔枝","柠檬"], table:[{litchi:"甜",lemon:"酸"}], keys:["litchi","lemon"], sheetName:"水果的味道" } ] } } 使用的这个示例。第一行 这个如何去掉。使用的 0.2版本，希望您能尽快回复下。谢谢 清风小阳 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "清风小阳" ***@***.***&gt;; 发送时间:&nbsp;2022年8月26日(星期五) 晚上6:01 ***@***.***&gt;; 主题:&nbsp;回复： [pikaz-18/pikaz-excel-js] 行数据太多。sheet[0].title 不居中 (#8) 今天发现 1.0.0版本出现组件无法注册情况，望处理下，谢谢
> ------------------ 原始邮件 ------------------ 发件人: "pikaz-18/pikaz-excel-js" ***@***.***&gt;; 发送时间:&nbsp;2020年7月24日(星期五) 上午9:25 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [pikaz-18/pikaz-excel-js] 行数据太多。sheet[0].title 不居中 (#8) 行数据中，列超过26个字母后，title为左对齐并且列未合并 可以给一份测试数据吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

第一行指的是标题吗，如果是标题，只要去掉title即可

**Comment by yang317621308** [comment]
好的，谢谢




清风小阳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pikaz-18/pikaz-excel-js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月14日(星期三) 上午10:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pikaz-18/pikaz-excel-js] 行数据太多。sheet[0].title 不居中 (#8)





  
import {ExcelExport} from 'pikaz-excel-js' ... export default { components: { ExcelExport, }, data () { return { sheet:[ { title:"水果的味道", tHeader:["荔枝","柠檬"], table:[{litchi:"甜",lemon:"酸"}], keys:["litchi","lemon"], sheetName:"水果的味道" } ] } } 使用的这个示例。第一行 这个如何去掉。使用的 0.2版本，希望您能尽快回复下。谢谢 清风小阳 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "清风小阳" @.&gt;; 发送时间:&nbsp;2022年8月26日(星期五) 晚上6:01 @.&gt;; 主题:&nbsp;回复： [pikaz-18/pikaz-excel-js] 行数据太多。sheet[0].title 不居中 (#8) 今天发现 1.0.0版本出现组件无法注册情况，望处理下，谢谢
 ------------------ 原始邮件 ------------------ 发件人: "pikaz-18/pikaz-excel-js" @.&gt;; 发送时间:&nbsp;2020年7月24日(星期五) 上午9:25 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [pikaz-18/pikaz-excel-js] 行数据太多。sheet[0].title 不居中 (#8) 行数据中，列超过26个字母后，title为左对齐并且列未合并 可以给一份测试数据吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
第一行指的是标题吗，如果是标题，只要去掉title即可
